### ISSUE TITLE
Website Error

### ISSUE THREAD

**Issue by yellowbrickwall** [rbtl-fs24/project-yellowbrickwall#1]
@larnsce My webpage link currently creates a 404 Error. Is this bad or is it just because there isn't really anything there yet?

**Comment by yellowbrickwall** [comment]
@larnsce @elizabeth-tilley @bonschorno Ignoring the error, I set everything else up :)

**Comment by bonschorno** [comment]
Hi @yellowbrickwall,
You haven't rendered your .qmd file yet, which means that there's no .html file that could be displayed on your website (see 404 error: "For root URLs (like http://example.com/) you must provide an *index.html* file.). Once you've created *index.html* and put it in the docs folder, it should be fine.

**Comment by yellowbrickwall** [comment]
@bonschorno Thanks, it should work now
